### ISSUE TITLE
Which  presonus-studiolive-api to use?

### ISSUE THREAD

**Issue by jbubik** [featherbear/bitfocus-companion-module-presonus-studiolive-iii#1]
Hello Andrew, I would like to help with this project. I see you made some refactoring in presonus-studiolive-api recently. I guess  bitfocus-companion-module-presonus-studiolive-iii will need some changes too. Please let me know if/when I can help. I am a complete beginner in TS/JS, but have some knowledge about other languages, system administration, networking. Our Companion runs on RaspberryPI4B / ubuntu 20.04 and our console is Presonus Studiolive 24R.

Current master of bitfocus-companion-module-presonus-studiolive-iii has these issues:
- depends on presonus-studiolive-api#db4183a6c3afec3bd1d035875785baedeb993095 (Mar 24, 2021)
- fails on RPi with this log message: `22.01.01 22:51:45 module(presonus-studiolive-iii): Error loading module: Error: Cannot find module './Actions' Require stack: - /opt/companion/module-local-dev/companion-module-presonus-studiolive-iii/node_modules/presonus-studiolive-api/dist/lib/constants/index.js - /opt/companion/module-local-dev/companion-module-presonus-studiolive-iii/node_modules/presonus-studiolive-api/dist/lib/MessageProtocol.js - /opt/companion/module-local-dev/companion-module-presonus-studiolive-iii/node_modules/presonus-studiolive-api/dist/lib/Discovery.js - /opt/companion/module-local-dev/companion-module-presonus-studiolive-iii/node_modules/presonus-studiolive-api/dist/lib/Client.js - /opt/companion/module-local-dev/companion-module-presonus-studiolive-iii/node_modules/presonus-studiolive-api/dist/api.js - /opt/companion/module-local-dev/companion-module-presonus-studiolive-iii/index.js - /opt/companion/lib/instance.js - /opt/companion/app.js - /opt/companion/headless_ip.js`
- root cause is `require('./Actions');` but the file name is `actions.js`; this fails on RPi/ext4 (case sensitive filesystem) while on Windows/NTFS (case insensitive filesystem) it probably works
- after renaming files in `node_modules/presonus-studiolive-api/dist/lib/constants/` to `Actions.js` / `Channels.js` / `MessageTypes.js` I can successfully mute/unmute the channels on Presonus console!

I have tried to replace presonus-studiolive-api with #95e52125911196db16f860e97e935fcb45981a99 (Jan 1, 2022). No error messages in Companion, but mute/unmute doesn't work. I noticed only a few dependencies pulled in with this release. The older code pulled dozens of packages.

**Comment by featherbear** [comment]
Hi @jbubik, thanks for taking interest in this integration.
As you've said, https://github.com/featherbear/presonus-studiolive-api/commit/db4183a6c3afec3bd1d035875785baedeb993095 is (moreorless) the last working version that I've developed this Companion integration against. Since then, alot of the structure has changed (_still trying to figure out what things to expose in the API!_)


RE: Case sensitive file naming - Yeah haha this has been a pain, because Windows' `git` client doesn't recognise case changing as a change; [I've since added a linter](https://github.com/featherbear/presonus-studiolive-api/commit/3903eb4f402ed030117a4c84520ccdf88c7103fc) in the pipeline to catch these things in the future!

---

I'm almost finished with my sprint (`v1.0.3`) of the API; and soon after I'll update this integration to support it - I'll let you know when that's done :)

**Comment by featherbear** [comment]
@jbubik Commit b3b556287f2f289c6b2cbf9341b3e856e2a7e4de should be stable, try it out :)

> [Module `v1.1.1`](https://github.com/featherbear/bitfocus-companion-module-presonus-studiolive/releases/tag/v1.1.1) built against [`API v1.0.5`](https://github.com/featherbear/presonus-studiolive-api/commit/f93b196c77727da60109f72ec9b2461a2f930a16) 

---

![help text](https://user-images.githubusercontent.com/1159091/147874935-bb080383-557b-40bc-a25d-b42fe482fc45.png)

![interface](https://user-images.githubusercontent.com/1159091/147874986-89842bb4-5242-45db-9efe-b6bfaddfc869.png)

**Comment by jbubik** [comment]
Works properly with our StudioLive 24R. Thank you!
